---
apiVersion: v1
kind: Namespace
metadata:
  name: gitea
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gitea-pvc
  namespace: gitea
  annotations:
    volume.beta.kubernetes.io/storage-class: "fast"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---  
kind: Deployment
apiVersion: apps/v1
metadata:
  name: gitea
  namespace: gitea
  labels:
    name: gitea
    app: gitea
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: gitea
  template:
    metadata:
      labels:
        app: gitea  
    spec:
      volumes:
      - name: gitea-volume
        persistentVolumeClaim:
          claimName: gitea-pvc    
      containers:
      - name: gitea
        image: "gitea/gitea:latest"    
---
apiVersion: v1
kind: Service
metadata:
  name: gitea
  namespace: gitea
  labels:
    name: gitea
spec:
  ports:
    - name: gitea
      port: 443
      targetPort: 3000
    - name: gitea-ssh
      port: 22
      targetPort: 22
  selector:
    name: gitea
  type: NodePort
  sessionAffinity: None
