---
apiVersion: v1
kind: Namespace
metadata:
  name: gitea
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gitea
  namespace: gitea
  annotations:
    volume.beta.kubernetes.io/storage-class: "fast"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---  
kind: Deployment
apiVersion: v1
metadata:
  name: gitea
  namespace: gitea
  labels:
    name: gitea
    app: gitea
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: gitea  
    spec:
      containers:
      - name: gitea
        image: "gitea/gitea:latest"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        - containerPort: 22          
      volumes:
      - name: gitea
        persistentVolumeClaim:
          claimName: gitea
       resources:
          requests:
            cpu: 10m
            memory: 50Mi
          limits:
            cpu: 1
            memory: 200Mi          
---
apiVersion: v1
kind: Service
metadata:
  name: gitea
  namespace: gitea
  labels:
    name: gitea
spec:
  ports:
    - name: gitea
      port: 443
      targetPort: 3000
    - name: gitea-ssh
      port: 22
      targetPort: 22
  selector:
    name: gitea
  type: NodePort
  sessionAffinity: None
