---
apiVersion: v1
kind: Namespace
metadata:
  name: gitea
  
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gitea
  namespace: gitea
  labels:
    name: gitea
    app: gitea
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: gitea  
    spec:
      # Initial rights settings when creating disk can be incorrect for the git user in the gitea container: Use init container to set the rights
      initContainers:
      - name: init-disk
        image: busybox:latest
        command:
        - /bin/chown
        - 1000:1000
        - /data
        volumeMounts:
        - name: gitea
          mountPath: "/data"
      containers:
      - name: gitea
        image: "gitea/gitea:latest"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        - containerPort: 22          
      volumes:
      - name: gitea
        persistentVolumeClaim:
          claimName: gitea
       resources:
          requests:
            cpu: 10m
            memory: 50Mi
          limits:
            cpu: 1
            memory: 200Mi          
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gitea
  namespace: gitea
  annotations:
    volume.beta.kubernetes.io/storage-class: "fast"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
